name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for contributing!' first issue"
        pr-message: "Hi, welcome to my Socket Chat Repo. I'm looking forward to see what you make of it.' first pull request"
